name: Clojure tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - uses: DeLaGuardo/setup-clojure@9.5
      with:
       cli: 1.11.1.1155
    - name: Run tests
      run: clojure -M:test:run-kaocha
